### ISSUE TITLE
I can turn off console with Node Red but can't turn it on.

### ISSUE THREAD

**Issue by IanLauder** [MPK44/node-red-contrib-xbox-smartglass#1]
I have a flow working that will send the "off" command and the console will turn off.

But sending the "on" command gives an error message in the debug log "Can't use Broadcast for turning on"

But I don't have it set to Broadcast, the node is configured for fixed parameters using the IP address and LiveId.   I've tried rebooting the Node Red server and restarting the browser but its still not working.  Fair warning - I'm new to using Node Red.

I did have the console being controlled just fine on/off using Hubitat with the Xbox Rest server and Alexa turns the console on/off fine.

How do I get this working to turn the console on?

![nodexbox](https://user-images.githubusercontent.com/80353713/110518854-80084080-80c1-11eb-9049-49e1c5100dcf.jpg)

**Comment by IanLauder** [comment]
Kind of new to Node Red, but took a crack at looking at the code.  I don't know why the values in the configuration HTML are not passing through to the .js code.  But that seems to be my issue.  I have the form filled out for the properties.  But the values are null when evaluated by the "on" code so it throws the error thinking its in Broadcast.  If I hardcode the ip and live id into the .js code it works fine.  Just don't know why its not passing between the html and .js code on my end.  Rebooted everything a couple times but that didn't help.

**Comment by MPK44** [comment]
Hello LanLauder,

somehow I missed the notitication. Will take a look at this soon.

**Comment by IanLauder** [comment]
Thanks, otherwise its been working since I hard coded the values into the code itself.  On another note, is it possible for the smartglass api to launch Xbox titles?   That's the only thing I'm missing and not sure how Alexa does it.  After I use the node red to turn on the Xbox, I use Alexa to launch an app like a specific game or YouTube.   It would be nice to have all the xbox commands contained in something that doesn't require Alexa.

**Comment by MPK44** [comment]
Hi,
just released a new version that will take into account the configuration used and not broadcast all the time. Can you confirm it fixes your problem?

About launching an app, that might be possible. I am using https://github.com/OpenXbox/xbox-smartglass-core-node . Any hints are highly welcome.

**Comment by IanLauder** [comment]
I'm not seeing where to download the update. The node red palette manager isn't showing an update button.   And the dates on the github page are showing the last update was Feb 10.

**Comment by MPK44** [comment]
should now also be visible in the palette manager

**Comment by IanLauder** [comment]
I did the update, stopped/restarted NR and double checked my ip/live id and even made a change to reset them and redeploy the flow.  I get the IP showing up but not the L
liveID.   So it wouldn't turn on the xbox.   I put a couple debug lines right before the on function to print the ip and node.liveID variables and IP was set but node.liveID is blank.

**Comment by MPK44** [comment]
I have missed this one.
Hope it works now (just pushed on git this time), cant test it right now with my box :(

**Comment by IanLauder** [comment]
That took care of the ip and liveid values.  The console does turn on/off now.  Its kind of spotty in how often it works, I have no idea where the glitches would be occurring.  Turning off the console with the NR node works fine, turning it on is spotty, I had to inject that node a couple times to get it to work.   In the NR log file I usually see:

Error: Syntax Error: Unexpected token o in JSON at position 1

This occurs all the time but doesn't seem to affect anything.

While testing this fix the times the console doesn't turn on via the NR node I see in the log:

[error] [Xbox-controller:Xbox] Xbox is unavailable on 192.168.50.224
...
[error] [Xbox-controller:Xbox] Console was not found on network. Probably failed.

But when I injected it a 2nd time without doing anything else it worked.   I do have the xbox on a wired connection with a static IP and Alexa never has an issue turning it on/off nor turning it on/off with a wireless controller.

And this is the 1st time I've seen this in the log.  After NR turned on the Xbox I got bunch of errors starting with an uncaught exception, then

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be between >= 0 and <=128. Received 19874 at bounds Error (internal/buffer.js:49:9)
followed by a bunch of errors in the xbox-smartglass-core-node files then it restarted Node Red.

**Comment by MPK44** [comment]
The only thing I could reproduce is the "Console was not found on network. Probably failed." error. You can double the default retries by changing the command to: `sgClient.powerOn({
          'ip': ip,
          'live_id': config.liveID,
          'tries': 10
        })` that should probably help quite well.

do you have more details on the uncaught exception?

The first error seems more like a misconfigured inject node.

**Comment by IanLauder** [comment]
I'm not getting any of the errors at the moment.  Watching the node red log file while I'm turning it on, off, and other commands like nexus button and I'm not seeing the json error messages anymore.  I'll keep an eye on it and if I see it happen again I'll update this post.  I added the retries as well.   I also have as a backup Alexa turns it on/off.   So they are kind of a backup to each other.   Every once in awhile neither one works and I have to use the controller.

**Comment by IanLauder** [comment]
I'm thinking the no json errors may be timing related in NR?  I'm relatively new to NR so figuring this stuff out reading other forum posts.  Sometimes the commands all go through fine with no log errors.  Sometimes I see those json errors:

Error: Syntax Error: Unexpected token o in JSON at position 1

Looking at my log file this morning I have a Hubitat routine that at midnight turns the whole home off and that flips a virtual switch that NR picks up that sends the payload "off" string to the Xbox node.   Last night it gave the JSON error above followed by the error message that the Xbox is unavailable on 192.169.50.224   

My node setup is pretty simple.  I have a hubitat node that detects a switch turned on.  That flows to a Change node that sets the payload to a string value of "on" or "off" depending on the switch.  That flows into the Xbox node.

I also have some Alexa nodes (unrelated to the Xbox nodes) that randomly fail with "no json" errors that other people seem to also have the same random errors with and they have tried all sorts of workarounds like catch nodes to retry the operations, adding delay nodes, etc all with varying degrees of success.

**Comment by MPK44** [comment]
Was the xbox on when you tried to turn it off and got the message "Xbox is unavailable on 192.169.50.224"? If not thats the reason. It just couldnt connect to turn it off.

about the JSON Errors I have no clue. Never hat these in my setup sofar.

**Comment by IanLauder** [comment]
I was just doing some more testing.  False alarm on the json errors, those are coming from someone elses custom Harmony Hub palette.  I happened to have a separate flow that was kicking off that at the same time the xbox one was being called.

The xbox is always off when I'm getting the Xbox is unavailable messages.  But usually even Alexa can't turn it on either.  If neither NR nor Alexa can turn it on is when I have to use the controller.  Haven't figured out that part yet but its probably outside the scope of NR/Alexa.  And its not always that its not able to turn it on.  It seems to be random at the moment.  Maybe something turns off after a length of time.  I'll have to keep an eye on it and see if I spot a pattern.

**Comment by MPK44** [comment]
I am using IR to turn on my XBOX as it is in powersaving mode. This as well as another idea is beeing worked on here: https://github.com/Vegz78/WakeXBOne
