### ISSUE TITLE
Can this be used to start games/apps on the xbox aswell ?

### ISSUE THREAD

**Issue by gelsas** [MPK44/node-red-contrib-xbox-smartglass#3]
It seems that other people using the smartglass core from OpenXbox (like ioBroker/Homeassistant are able to start games via their integrations?

If it is possible, how can I do it with this node red integration?

**Comment by MPK44** [comment]
For this plugin OpenXbox / xbox-smartglass-core-node, which does not have the functionality to launch an app.

But are you sure it is still working with ioBroker etc?
https://github.com/foxriver76/ioBroker.xbox/issues/39

**Comment by gelsas** [comment]
Yes it is still working for iobroker etc.
